### ISSUE TITLE
Проект

### ISSUE THREAD

**Issue by Poisondo** [hobbyquaker/ccu.io#159]
Добрый день!

Подскажите, проект будет в дальнейшем дорабатываться и поддерживаться, или его можно считать законченным?

**Comment by GermanBluefox** [comment]
Именно этот проект закончен. Но он развивается дальше в проекте ioBroker.
Тот же концепт, только все лучше и продуманней. И та же команда.

Посмотрите здесь: http://iobroker.net

http://forum.iobroker.net

https://github.com/ioBroker

5 Окт 2016 г. 11:01 пользователь "Poisondo" <notifications@github.com>
написал:
